INSERT INTO AUTOR (id, nombre) values (1,'Ken Follett');
INSERT INTO AUTOR (id, nombre) values (2,'Eva García Sáenz de Urturi');
INSERT INTO AUTOR (id, nombre) values (3,'Astrid Nilsen');
INSERT INTO AUTOR (id, nombre) values (4,'Bram Stoker');
INSERT INTO AUTOR (id, nombre) values (5,'Mary Shelley');
INSERT INTO AUTOR (id, nombre) values (6,'Andy Weir');
INSERT INTO AUTOR (id, nombre) values (7,'Stephen King');
INSERT INTO AUTOR (id, nombre) values (8,'Ernest Cline');
INSERT INTO AUTOR (id, nombre) values (9,'Juan Gómez-Jurado');
INSERT INTO AUTOR (id, nombre) values (10,'Umberto Eco');
INSERT INTO AUTOR (id, nombre) values (11, 'Ben Kane');
INSERT INTO AUTOR (id, nombre) values (12, 'Isaac Asimov');
INSERT INTO AUTOR (id, nombre) values (13, 'Robert Kirkman');
INSERT INTO AUTOR (id, nombre) values (14, 'J.R.R. Tolkien');