INSERT INTO CATEGORIA (id, nombre) values (1,'Ciencia Ficción');
INSERT INTO CATEGORIA (id, nombre) values (2,'Novela Negra');
INSERT INTO CATEGORIA (id, nombre) values (3,'Terror');
INSERT INTO CATEGORIA (id, nombre) values (4,'Romántica');
INSERT INTO CATEGORIA (id, nombre) values (5,'Ensayo');
INSERT INTO CATEGORIA (id, nombre) values (6,'Cómic');
INSERT INTO CATEGORIA (id, nombre) values (7,'Suspense');
INSERT INTO CATEGORIA (id, nombre) values (8,'Policiaca');
INSERT INTO CATEGORIA (id, nombre) values (9,'Aventuras');
INSERT INTO CATEGORIA (id, nombre) values (10,'Ficción Histórica');
INSERT INTO CATEGORIA (id, nombre) values (11,'Fantasía');